spring:
  datasource:
    url: jdbc:mysql://localhost:{port}/{dbname}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {username}
    password: {password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secretKey: 29a5f10aff5fb4d92c464240b8c976f044bed2c96557b5fab2f33d8e0c8d5466
  refreshExp: 604800000 # 1주
  accessExp: 6000000 # 2시간