spring:
  datasource:
    url: jdbc:mysql://localhost:{포트번호}/{데이터베이스 이름}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {username}
    password: {password}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

application:
  jwt:
    secret: {secretKey}
    refreshExp: 604800000 # 1?
    accessExp: 6000000 # 2??

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
